# Generated by Django 4.1.3 on 2023-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
